version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"    
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"
    container_name: "database"
    hostname: "database"
  tools:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile.DbBuilder
    image: standalone-tools:latest
    links:
      - 'db:database'
    depends_on:
      - 'db'
 